// Build design tokens with Style Dictionary v5 from DTCG (2025.10) sources.
//
// Ingests the same shape a Figma export produces: `$value`/`$type`, OKLCH colour
// objects, dimension objects, aliases, and `$extensions.mode` theming.
//
// Output:
//   dist/css/tokens.css        — CSS custom properties, themed via :root / [data-theme]
//   dist/nativewind/preset.cjs — a Tailwind v3-shaped preset for NativeWind (RN)
//
// Theming model: tokens with no mode (spacing/radius/shadow) live on :root. Colour
// tokens carry per-mode values; the default mode ("nova") is emitted on :root as
// well as [data-theme="nova"], other modes on their own [data-theme] scope. A
// switch is a single attribute flip — the custom properties re-resolve live.
import StyleDictionary from 'style-dictionary'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { collectModes, filterTree, forMode, hasRealMode, registerDtcgTransforms } from '../lib/dtcg.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const SRC = path.join(root, 'src/tokens')

// All custom-property names are namespaced `--ds-*` so they never collide with
// Tailwind v4's own `@theme`-generated variables.
const PREFIX = 'ds'
const DEFAULT_MODE = 'nova'
const SOURCE_FILES = ['base.tokens.json', 'color.tokens.json']

function deepMerge(target, source) {
  for (const [key, value] of Object.entries(source)) {
    if (value && typeof value === 'object' && !Array.isArray(value) && target[key] && typeof target[key] === 'object') {
      deepMerge(target[key], value)
    } else {
      target[key] = value
    }
  }
  return target
}

registerDtcgTransforms(StyleDictionary)

// CSS custom properties wrapped in a caller-supplied selector.
StyleDictionary.registerFormat({
  name: 'css/themed-variables',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root'
    const body = dictionary.allTokens.map((token) => `  --${PREFIX}-${token.name}: ${token.$value};`).join('\n')
    return `${selector} {\n${body}\n}\n`
  },
})

// A NativeWind-compatible Tailwind v3 preset (compatible export only — see README).
StyleDictionary.registerFormat({
  name: 'javascript/nativewind-preset',
  format: ({ dictionary }) => {
    const bucket = { color: 'colors', spacing: 'spacing', radius: 'borderRadius', shadow: 'boxShadow' }
    const theme = { colors: {}, spacing: {}, borderRadius: {}, boxShadow: {} }
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path
      const target = theme[bucket[group]]
      if (target) target[rest.join('-')] = `var(--${PREFIX}-${token.name})`
    }
    return (
      '/** AUTO-GENERATED by @scottmallin/tokens — do not edit by hand. */\n' +
      `module.exports = ${JSON.stringify({ theme: { extend: theme } }, null, 2)}\n`
    )
  },
})

const TRANSFORMS = ['name/kebab', 'dtcg/color', 'dtcg/dimension']

function cssPlatform(tokens, selector, destination) {
  return new StyleDictionary({
    tokens,
    usesDtcg: true,
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: 'dist/css/',
        files: [{ destination, format: 'css/themed-variables', options: { selector } }],
      },
    },
  })
}

async function run() {
  // Load + merge DTCG sources.
  const tree = {}
  for (const file of SOURCE_FILES) {
    deepMerge(tree, JSON.parse(await fs.readFile(path.join(SRC, file), 'utf8')))
  }

  // Discover modes; put the default first.
  const modes = [...collectModes(tree)]
  const orderedModes = [DEFAULT_MODE, ...modes.filter((m) => m !== DEFAULT_MODE)].filter((m) => modes.includes(m))

  const base = filterTree(tree, (token) => !hasRealMode(token)) ?? {}
  const themed = filterTree(tree, hasRealMode) ?? {}

  // :root — mode-independent primitives.
  await cssPlatform(base, ':root', 'base.css').buildAllPlatforms()

  // Per-mode themed blocks; the default mode also lands on :root.
  for (const mode of orderedModes) {
    const selector = mode === DEFAULT_MODE ? `:root,\n[data-theme="${mode}"]` : `[data-theme="${mode}"]`
    await cssPlatform(forMode(themed, mode), selector, `${mode}.css`).buildAllPlatforms()
  }

  // Concatenate: base + default first, then the remaining modes.
  const cssDir = path.join(root, 'dist/css')
  const parts = []
  for (const file of ['base.css', ...orderedModes.map((m) => `${m}.css`)]) {
    parts.push(await fs.readFile(path.join(cssDir, file), 'utf8'))
  }
  const header =
    '/**\n' +
    ' * AUTO-GENERATED design tokens — do not edit by hand.\n' +
    ' * Source: DTCG (2025.10) with $extensions.mode theming.\n' +
    ' * Rebuild: `pnpm --filter @scottmallin/tokens build`\n' +
    ` * Default mode "${DEFAULT_MODE}" on :root; other modes via [data-theme].\n` +
    ' */\n'
  await fs.writeFile(path.join(cssDir, 'tokens.css'), header + parts.join('\n'), 'utf8')

  // NativeWind preset from the full default-mode token set.
  const full = deepMerge(JSON.parse(JSON.stringify(base)), forMode(themed, DEFAULT_MODE))
  await new StyleDictionary({
    tokens: full,
    usesDtcg: true,
    log: { verbosity: 'silent' },
    platforms: {
      nativewind: {
        transforms: TRANSFORMS,
        buildPath: 'dist/nativewind/',
        files: [{ destination: 'preset.cjs', format: 'javascript/nativewind-preset' }],
      },
    },
  }).buildAllPlatforms()

  console.log(`✓ tokens built (DTCG, modes: ${orderedModes.join(', ')}) → dist/css/tokens.css, dist/nativewind/preset.cjs`)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
