// Build design tokens with Style Dictionary v5.
//
// Output:
//   dist/css/tokens.css        — CSS custom properties, themed via :root / [data-theme]
//   dist/nativewind/preset.cjs — a Tailwind v3-shaped preset for NativeWind (RN)
//
// Theming model (web): brand-agnostic tokens (spacing/radius/shadow) live on :root.
// Colour tokens are per-brand; "nova" is the default (emitted on :root as well as
// [data-theme="nova"]), "ember" is opt-in via [data-theme="ember"]. Switching a
// theme is a single attribute flip — the CSS custom properties re-resolve live.
import StyleDictionary from 'style-dictionary'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

// All custom-property names are namespaced `--ds-*` so they never collide with
// Tailwind v4's own `@theme`-generated `--color-*` / `--spacing-*` variables.
const PREFIX = 'ds'

// --- custom formats -------------------------------------------------------

// CSS custom properties wrapped in a caller-supplied selector, so the same token
// set can be emitted onto :root or a [data-theme="…"] scope.
StyleDictionary.registerFormat({
  name: 'css/themed-variables',
  format: ({ dictionary, options }) => {
    const selector = options.selector ?? ':root'
    const body = dictionary.allTokens
      .map((token) => `  --${PREFIX}-${token.name}: ${token.value};`)
      .join('\n')
    return `${selector} {\n${body}\n}\n`
  },
})

// A NativeWind-compatible Tailwind v3 preset. NOTE (see README): this is a
// *compatible export* — the same semantic class names exist in RN — not a claim
// of runtime [data-theme] parity with the web build.
StyleDictionary.registerFormat({
  name: 'javascript/nativewind-preset',
  format: ({ dictionary }) => {
    const colors = {}
    const spacing = {}
    const borderRadius = {}
    const boxShadow = {}
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path
      const key = rest.join('-')
      const cssVar = `var(--${PREFIX}-${token.name})`
      if (group === 'color') colors[key] = cssVar
      else if (group === 'spacing') spacing[key] = cssVar
      else if (group === 'radius') borderRadius[key] = cssVar
      else if (group === 'shadow') boxShadow[key] = cssVar
    }
    const preset = { theme: { extend: { colors, spacing, borderRadius, boxShadow } } }
    return (
      '/** AUTO-GENERATED by @scottmallin/tokens — do not edit by hand. */\n' +
      `module.exports = ${JSON.stringify(preset, null, 2)}\n`
    )
  },
})

// Only kebab-case the token names; leave authored values (rem strings, rgba(),
// hex, "none") untouched. No CTI/size transforms to mangle pre-unitted values.
const TRANSFORMS = ['name/kebab']

function cssPlatform(selector, source, destination) {
  return new StyleDictionary({
    source,
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: 'dist/css/',
        files: [{ destination, format: 'css/themed-variables', options: { selector } }],
      },
    },
  })
}

const glob = (p) => path.join(root, p).replace(/\\/g, '/')

async function run() {
  const base = [glob('src/tokens/base/*.json')]
  const nova = [glob('src/tokens/brands/nova/*.json')]
  const ember = [glob('src/tokens/brands/ember/*.json')]

  // Emit selector-scoped partials.
  await cssPlatform(':root', base, 'base.css').buildAllPlatforms()
  await cssPlatform(':root,\n[data-theme="nova"]', nova, 'nova.css').buildAllPlatforms()
  await cssPlatform('[data-theme="ember"]', ember, 'ember.css').buildAllPlatforms()

  // Concatenate partials into a single importable stylesheet.
  const cssDir = path.join(root, 'dist/css')
  const parts = []
  for (const file of ['base.css', 'nova.css', 'ember.css']) {
    parts.push(await fs.readFile(path.join(cssDir, file), 'utf8'))
  }
  const header =
    '/**\n' +
    ' * AUTO-GENERATED design tokens — do not edit by hand.\n' +
    ' * Rebuild: `pnpm --filter @scottmallin/tokens build`\n' +
    ' * Default theme is "nova" (:root); opt into "ember" via [data-theme="ember"].\n' +
    ' */\n'
  await fs.writeFile(path.join(cssDir, 'tokens.css'), header + parts.join('\n'), 'utf8')

  // NativeWind preset needs every category, so build from base + one brand's
  // structure (semantic names are identical across brands).
  await new StyleDictionary({
    source: [...base, ...nova],
    log: { verbosity: 'silent' },
    platforms: {
      nativewind: {
        transforms: TRANSFORMS,
        buildPath: 'dist/nativewind/',
        files: [{ destination: 'preset.cjs', format: 'javascript/nativewind-preset' }],
      },
    },
  }).buildAllPlatforms()

  console.log('✓ tokens built → dist/css/tokens.css, dist/nativewind/preset.cjs')
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
